// src/lib/styles/cityCosts.ts
import { tv } from "tailwind-variants";

export const cityCostsVariants = tv({
  slots: {
    container: [
      "space-y-6",
    ],
    filterBar: [
      "bg-white",
      "rounded-2xl",
      "p-6",
      "shadow-sm",
      "flex",
      "flex-wrap",
      "gap-4",
      "items-center",
    ],
    selectWrapper: [
      "flex-1",
      "min-w-[200px]",
    ],
    label: [
      "text-xs",
      "text-[#6B7280]",
      "uppercase",
      "tracking-wide",
      "mb-2",
      "font-semibold",
      "font-inter",
    ],
    select: [
      "w-full",
      "px-4",
      "py-2",
      "border",
      "border-gray-200",
      "rounded-lg",
      "bg-white",
      "text-[#1F2A44]",
      "font-inter",
      "focus:outline-none",
      "focus:ring-2",
      "focus:ring-[#2BD4A2]",
    ],
    compareButton: [
      "px-6",
      "py-2",
      "bg-[#2BD4A2]",
      "text-white",
      "rounded-lg",
      "font-semibold",
      "hover:bg-[#25B D91]",
      "transition-colors",
      "font-inter",
    ],
    cityCard: [
      "bg-white",
      "rounded-2xl",
      "p-6",
      "shadow-sm",
    ],
    cityHeader: [
      "flex",
      "items-center",
      "justify-between",
      "mb-6",
    ],
    cityTitle: [
      "flex",
      "items-center",
      "gap-3",
    ],
    cityName: [
      "text-2xl",
      "font-bold",
      "text-[#1F2A44]",
      "font-cormorant",
    ],
    costSummary: [
      "text-right",
    ],
    totalCost: [
      "text-3xl",
      "font-bold",
      "text-[#2BD4A2]",
      "font-inter",
    ],
    perMonth: [
      "text-xs",
      "text-[#6B7280]",
      "font-inter",
    ],
    categorySection: [
      "mb-6",
      "last:mb-0",
    ],
    categoryHeader: [
      "flex",
      "items-center",
      "gap-2",
      "mb-4",
      "pb-2",
      "border-b",
      "border-gray-200",
    ],
    categoryTitle: [
      "text-lg",
      "font-bold",
      "text-[#1F2A44]",
      "font-cormorant",
    ],
    categoryIcon: [
      "w-5",
      "h-5",
      "text-[#2BD4A2]",
    ],
    costGrid: [
      "grid",
      "grid-cols-1",
      "md:grid-cols-2",
      "gap-4",
    ],
    costItem: [
      "flex",
      "justify-between",
      "items-center",
      "p-3",
      "bg-gray-50",
      "rounded-lg",
    ],
    costLabel: [
      "text-sm",
      "text-[#1F2A44]",
      "font-inter",
    ],
    costValue: [
      "text-sm",
      "font-bold",
      "text-[#1F2A44]",
      "font-inter",
    ],
    comparisonGrid: [
      "grid",
      "grid-cols-1",
      "md:grid-cols-2",
      "gap-6",
    ],
  },
});