// src/lib/styles/blog.ts
import { tv } from "tailwind-variants";

export const blogVariants = tv({
  slots: {
    container: [
      "w-full",
      "max-w-[80%]",
      "mx-auto",
      "space-y-8",
      "animate-in",
      "fade-in",
      "duration-500",
    ],
    header: [
      "mb-8",
    ],
    title: [
      "text-[2rem]",
      "lg:text-[2.5rem]",
      "font-bold",
      "text-[#1F2A44]",
      "mb-3",
      "font-cormorant",
    ],
    subtitle: [
      "text-[0.875rem]",
      "lg:text-[1rem]",
      "text-[#6B7280]",
      "font-inter",
    ],
    featuredCard: [
      "bg-white",
      "rounded-2xl",
      "overflow-hidden",
      "shadow-sm",
      "hover:shadow-md",
      "transition-all",
      "duration-300",
      "mb-8",
      "grid",
      "grid-cols-1",
      "md:grid-cols-2",
      "gap-0",
    ],
    featuredImage: [
      "h-64",
      "md:h-full",
      "w-full",
      "bg-gradient-to-br",
      "from-[#2BD4A2]",
      "to-[#1F2A44]",
    ],
    featuredContent: [
      "p-6",
      "lg:p-8",
      "flex",
      "flex-col",
      "justify-center",
    ],
    featuredTitle: [
      "text-[1.5rem]",
      "lg:text-[2rem]",
      "font-bold",
      "text-[#1F2A44]",
      "mb-3",
      "font-cormorant",
    ],
    featuredExcerpt: [
      "text-[0.875rem]",
      "text-[#6B7280]",
      "mb-4",
      "font-inter",
      "line-clamp-3",
    ],
    category: [
      "inline-block",
      "px-3",
      "py-1",
      "bg-[#2BD4A2]/10",
      "text-[#2BD4A2]",
      "rounded-full",
      "text-[0.75rem]",
      "font-semibold",
      "mb-3",
      "font-inter",
    ],
    meta: [
      "flex",
      "flex-wrap",
      "items-center",
      "gap-2",
      "text-[0.75rem]",
      "text-[#9CA3AF]",
      "font-inter",
      "mb-4",
    ],
    author: [
      "flex",
      "items-center",
      "gap-2",
    ],
    avatar: [
      "w-6",
      "h-6",
      "rounded-full",
      "bg-gradient-to-br",
      "from-[#2BD4A2]",
      "to-[#1F2A44]",
    ],
    readMore: [
      "inline-flex",
      "items-center",
      "gap-2",
      "text-[0.875rem]",
      "text-[#2BD4A2]",
      "font-semibold",
      "hover:gap-3",
      "transition-all",
      "font-inter",
    ],
    grid: [
      "grid",
      "grid-cols-1",
      "sm:grid-cols-2",
      "lg:grid-cols-3",
      "gap-6",
    ],
    card: [
      "bg-white",
      "rounded-2xl",
      "overflow-hidden",
      "shadow-sm",
      "hover:shadow-md",
      "transition-all",
      "duration-300",
      "cursor-pointer",
      "group",
    ],
    imageWrapper: [
      "relative",
      "h-48",
      "overflow-hidden",
      "bg-gradient-to-br",
      "from-[#2BD4A2]",
      "to-[#1F2A44]",
    ],
    image: [
      "w-full",
      "h-full",
      "group-hover:scale-105",
      "transition-transform",
      "duration-300",
    ],
    content: [
      "p-5",
    ],
    cardTitle: [
      "text-[1.125rem]",
      "font-bold",
      "text-[#1F2A44]",
      "mb-2",
      "line-clamp-2",
      "group-hover:text-[#2BD4A2]",
      "transition-colors",
      "font-cormorant",
    ],
    excerpt: [
      "text-[0.875rem]",
      "text-[#6B7280]",
      "line-clamp-3",
      "mb-3",
      "font-inter",
    ],
  },
});