// src/lib/styles/dashboard.ts
import { tv } from "tailwind-variants";

export const dashboardVariants = tv({
  slots: {
    layout: [
      "flex",
      "min-h-screen",
      "bg-[#E8E4E1]",
    ],
    sidebar: [
      "w-[280px]",
      "bg-white",
      "border-r",
      "border-gray-200",
      "flex",
      "flex-col",
      "fixed",
      "h-screen",
      "overflow-y-auto",
      "transition-transform",
      "duration-300",
      "z-50",
    ],
    sidebarOverlay: [
      "fixed",
      "inset-0",
      "bg-black/50",
      "lg:hidden",
      "z-40",
      "transition-opacity",
      "duration-300",
    ],
    mobileMenuButton: [
      "lg:hidden",
      "fixed",
      "top-4",
      "left-4",
      "z-50",
      "p-2",
      "bg-white",
      "rounded-lg",
      "shadow-lg",
    ],
    sidebarContent: [
      "flex",
      "flex-col",
      "h-full",
      "p-6",
    ],
    logo: [
      "mb-8",
    ],
    logoText: [
      "text-[1.25rem]",
      "font-bold",
      "text-[#1F2A44]",
      "font-cormorant",
    ],
    logoAccent: [
      "text-[#D97757]",
      "text-[0.625rem]",
      "uppercase",
      "tracking-wider",
      "font-inter",
    ],
    section: [
      "mb-6",
    ],
    sectionTitle: [
      "text-[0.625rem]",
      "uppercase",
      "tracking-wider",
      "text-[#9CA3AF]",
      "mb-3",
      "font-semibold",
      "font-inter",
    ],
    navItem: [
      "flex",
      "items-center",
      "gap-3",
      "px-3",
      "py-2.5",
      "rounded-lg",
      "text-[0.875rem]",
      "transition-all",
      "duration-200",
      "cursor-pointer",
      "group",
      "font-inter",
      "mb-1",
    ],
    navIcon: [
      "w-5",
      "h-5",
      "transition-transform",
      "duration-200",
      "group-hover:scale-110",
    ],
    countryList: [
      "space-y-1",
      "mt-4",
    ],
    countryItem: [
      "flex",
      "items-center",
      "justify-between",
      "px-3",
      "py-2",
      "rounded-lg",
      "text-[0.875rem]",
      "transition-all",
      "duration-200",
      "cursor-pointer",
      "group",
      "font-inter",
    ],
    countryContent: [
      "flex",
      "items-center",
      "gap-2",
    ],
    flag: [
      "text-xl",
    ],
    removeButton: [
      "opacity-0",
      "group-hover:opacity-100",
      "transition-opacity",
      "p-1",
      "hover:bg-red-50",
      "rounded",
    ],
    addButton: [
      "flex",
      "items-center",
      "gap-2",
      "px-3",
      "py-2",
      "text-[0.875rem]",
      "text-[#6B7280]",
      "hover:text-[#1F2A44]",
      "hover:bg-gray-50",
      "rounded-lg",
      "transition-all",
      "cursor-pointer",
      "font-inter",
      "mt-2",
    ],
    bottomNav: [
      "mt-auto",
      "pt-6",
      "border-t",
      "border-gray-200",
      "space-y-1",
    ],
    mainContent: [
      "flex-1",
      "lg:ml-[140px]",
      "p-4",
      "lg:p-8",
      "transition-all",
      "duration-300",
    ],
    header: [
      "flex",
      "flex-col",
      "lg:flex-row",
      "lg:items-center",
      "justify-between",
      "gap-4",
      "mb-8",
    ],
    pageTitle: [
      "flex",
      "items-center",
      "gap-3",
      "text-[1.75rem]",
      "lg:text-[2rem]",
      "font-bold",
      "text-[#1F2A44]",
      "font-cormorant",
    ],
    tabs: [
      "flex",
      "gap-2",
      "bg-white",
      "rounded-full",
      "p-1",
      "shadow-sm",
      "w-fit",
    ],
    tab: [
      "px-4",
      "lg:px-6",
      "py-2",
      "rounded-full",
      "text-[0.875rem]",
      "font-medium",
      "transition-all",
      "cursor-pointer",
      "font-inter",
      "whitespace-nowrap",
    ],
    visaCard: [
      "bg-white",
      "rounded-2xl",
      "p-4",
      "lg:p-6",
      "transition-all",
      "duration-300",
      "hover:shadow-lg",
      "mb-4",
    ],
    cardHeader: [
      "flex",
      "flex-col",
      "lg:flex-row",
      "lg:items-center",
      "justify-between",
      "gap-4",
      "mb-6",
    ],
    cardTitle: [
      "flex",
      "items-center",
      "gap-3",
    ],
    cardTitleText: [
      "text-[1.125rem]",
      "lg:text-[1.25rem]",
      "font-bold",
      "text-[#1F2A44]",
      "font-cormorant",
    ],
    cardSubtitle: [
      "text-[#6B7280]",
      "font-inter",
      "text-[0.875rem]",
      "lg:text-base",
    ],
    badges: [
      "flex",
      "flex-wrap",
      "items-center",
      "gap-3",
    ],
    durationBadge: [
      "text-[0.875rem]",
      "font-semibold",
      "text-[#1F2A44]",
      "font-inter",
    ],
    visaBadge: [
      "px-3",
      "lg:px-4",
      "py-1.5",
      "rounded-full",
      "text-[0.75rem]",
      "lg:text-[0.875rem]",
      "font-medium",
      "font-inter",
    ],
    expandButton: [
      "flex",
      "items-center",
      "gap-2",
      "text-[0.875rem]",
      "text-[#2BD4A2]",
      "hover:text-[#25BD91]",
      "font-medium",
      "transition-colors",
      "cursor-pointer",
      "font-inter",
      "mt-4",
    ],
    requirementsSection: [
      "overflow-hidden",
      "transition-all",
      "duration-300",
    ],
    sectionLabel: [
      "text-[0.75rem]",
      "uppercase",
      "tracking-wider",
      "text-[#6B7280]",
      "font-semibold",
      "mb-3",
      "font-inter",
    ],
    requirementsList: [
      "space-y-2",
      "mb-4",
    ],
    requirementItem: [
      "flex",
      "items-start",
      "gap-2",
      "text-[0.875rem]",
      "text-[#1F2A44]",
      "font-inter",
    ],
    bullet: [
      "w-1.5",
      "h-1.5",
      "rounded-full",
      "bg-[#1F2A44]",
      "mt-1.5",
      "flex-shrink-0",
    ],
    benefits: [
      "flex",
      "flex-wrap",
      "gap-4",
      "lg:gap-6",
      "pt-4",
      "border-t",
      "border-gray-100",
    ],
    benefit: [
      "flex",
      "items-center",
      "gap-2",
      "text-[0.875rem]",
      "text-[#1F2A44]",
      "font-inter",
    ],
    emptyState: [
      "text-center",
      "py-12",
    ],
    emptyText: [
      "text-[#6B7280]",
      "mb-4",
      "font-inter",
    ],
  },
  variants: {
    active: {
      true: {
        navItem: [
          "bg-[#FFF8F5]",
          "text-[#1F2A44]",
          "font-semibold",
        ],
        tab: [
          "bg-white",
          "text-[#1F2A44]",
          "shadow-sm",
        ],
        countryItem: [
          "bg-[#FFF8F5]",
          "text-[#1F2A44]",
        ],
      },
      false: {
        navItem: [
          "text-[#6B7280]",
          "hover:bg-gray-50",
          "hover:text-[#1F2A44]",
        ],
        tab: [
          "text-[#6B7280]",
          "hover:text-[#1F2A44]",
          "hover:bg-gray-50",
        ],
        countryItem: [
          "text-[#6B7280]",
          "hover:bg-gray-50",
          "hover:text-[#1F2A44]",
        ],
      },
    },
    visaType: {
      digital: {
        visaBadge: [
          "bg-[#DBEAFE]",
          "text-[#1E40AF]",
        ],
      },
      investment: {
        visaBadge: [
          "bg-[#FED7AA]",
          "text-[#C2410C]",
        ],
      },
      freelance: {
        visaBadge: [
          "bg-[#D1FAE5]",
          "text-[#065F46]",
        ],
      },
    },
    sidebarOpen: {
      true: {
        sidebar: [
          "translate-x-0",
        ],
        sidebarOverlay: [
          "opacity-100",
          "pointer-events-auto",
        ],
      },
      false: {
        sidebar: [
          "-translate-x-full",
          "lg:translate-x-0",
        ],
        sidebarOverlay: [
          "opacity-0",
          "pointer-events-none",
        ],
      },
    },
    expanded: {
      true: {
        requirementsSection: [
          "max-h-[1000px]",
          "opacity-100",
        ],
      },
      false: {
        requirementsSection: [
          "max-h-0",
          "opacity-0",
        ],
      },
    },
  },
});