import { tv } from "tailwind-variants";
export const finalizeProfileModalVariants = tv({
  slots: {
    overlay: [
      "fixed",
      "inset-0",
      "z-50",
      "flex",
      "justify-center",
      "items-center",
      "transition-opacity",
      "duration-300",
    ],
    backdrop: [
      "fixed",
      "inset-0",
      "bg-black",
      "bg-opacity-100",
      "transition-opacity",
      "duration-300",
    ],
    modal: [
      "relative",
      "flex",
      "flex-col",
      "gap-[24px]",
      "w-[90%]",
      "max-w-[343px]",
      "bg-[#F4F0EF]",
      "rounded-[16px]",
      "p-[24px]",
      "transition-all",
      "duration-300",
      "transform",
      "md:max-w-[553px]",
      "md:p-[42px_36px_36px_36px]",
    ],
    title: [
      "text-[24px]",
      "font-bold",
      "text-[#1F2A44]",
      "text-center",
      "leading-[32px]",
      "md:text-[30px]",
      "md:leading-[40px]",
      "font-cormorant",
    ],
    description: [
      "text-[14px]",
      "text-[#6B7280]",
      "text-center",
      "leading-[20px]",
      "flex-1",
      "md:text-[16px]",
      "md:leading-[24px]",
      "font-inter",
    ],
    buttonsWrapper: [
      "flex",
      "flex-col",
      "gap-[16px]",
      "sm:flex-row",
      "sm:justify-between",
      "mt-auto",
    ],
    editButton: [
      "flex",
      "items-center",
      "gap-[8px]",
      "text-[#6B7280]",
      "text-[14px]",
      "leading-[20px]",
      "hover:text-[#1F2A44]",
      "transition-colors",
      "md:text-[16px]",
      "md:leading-[24px]",
      "font-inter",
    ],
    finalizeButton: [
      "flex",
      "items-center",
      "gap-[8px]",
      "bg-[#1F2A44]",
      "text-white",
      "rounded-[16px]",
      "px-[24px]",
      "py-[12px]",
      "text-[14px]",
      "leading-[20px]",
      "md:text-[16px]",
      "md:leading-[24px]",
      "hover:bg-[#374151]",
      "transition-colors",
      "font-inter",
    ],
    icon: [
      "w-[20px]",
      "h-[20px]",
    ],
  },
  variants: {
    visibility: {
      open: {
        overlay: "opacity-100",
        backdrop: "opacity-100",
        modal: "scale-100 opacity-100",
      },
      closing: {
        overlay: "opacity-0",
        backdrop: "opacity-0",
        modal: "scale-95 opacity-0",
      },
    },
  },
});