// src/lib/styles/settings.ts
import { tv } from "tailwind-variants";

export const settingsVariants = tv({
  slots: {
    container: [
      "w-full",
      "max-w-[1000px]",
      "mx-auto",
      "space-y-6",
      "animate-in",
      "fade-in",
      "duration-500",
    ],
    header: [
      "mb-6",
    ],
    title: [
      "text-[2rem]",
      "font-bold",
      "text-[#1F2A44]",
      "mb-2",
      "font-cormorant",
    ],
    subtitle: [
      "text-[0.875rem]",
      "text-[#6B7280]",
      "font-inter",
    ],
    upgradeCard: [
      "bg-gradient-to-br",
      "from-[#1F2A44]",
      "to-[#2A3A5C]",
      "rounded-2xl",
      "p-6",
      "lg:p-8",
      "relative",
      "overflow-hidden",
      "shadow-lg",
      "shadow-pink-900/20",
      "mb-6",
    ],
    upgradeContent: [
      "relative",
      "z-10",
    ],
    upgradeText: [
      "text-white",
      "text-[0.875rem]",
      "lg:text-[1rem]",
      "mb-4",
      "font-inter",
    ],
    upgradeButton: [
      "bg-white",
      "text-[#1F2A44]",
      "px-6",
      "lg:px-8",
      "py-3",
      "lg:py-4",
      "rounded-2xl",
      "font-bold",
      "text-[0.875rem]",
      "lg:text-[1rem]",
      "hover:bg-gray-100",
      "transition-all",
      "duration-200",
      "shadow-lg",
      "inline-block",
      "font-inter",
    ],
    upgradeNote: [
      "text-white/60",
      "text-[0.75rem]",
      "mt-2",
      "block",
      "font-inter",
    ],
    card: [
      "bg-white",
      "rounded-2xl",
      "p-5",
      "lg:p-6",
      "shadow-sm",
    ],
    sectionTitle: [
      "text-[1.125rem]",
      "lg:text-[1.25rem]",
      "font-bold",
      "text-[#1F2A44]",
      "mb-4",
      "font-cormorant",
    ],
    formGroup: [
      "mb-4",
    ],
    label: [
      "block",
      "text-[0.875rem]",
      "font-medium",
      "text-[#1F2A44]",
      "mb-2",
      "font-inter",
    ],
    input: [
      "w-full",
      "px-4",
      "py-2.5",
      "border",
      "border-gray-200",
      "rounded-xl",
      "bg-white",
      "text-[#1F2A44]",
      "text-[0.875rem]",
      "font-inter",
      "focus:outline-none",
      "focus:ring-2",
      "focus:ring-[#2BD4A2]",
      "focus:border-transparent",
      "transition-all",
    ],
    switchWrapper: [
      "flex",
      "items-center",
      "justify-between",
      "py-3",
      "border-b",
      "border-gray-100",
      "last:border-0",
    ],
    switchLabel: [
      "text-[0.875rem]",
      "text-[#1F2A44]",
      "font-inter",
    ],
    switch: [
      "relative",
      "inline-flex",
      "h-6",
      "w-11",
      "items-center",
      "rounded-full",
      "transition-colors",
      "cursor-pointer",
      "focus:outline-none",
      "focus:ring-2",
      "focus:ring-[#2BD4A2]",
      "focus:ring-offset-2",
    ],
    switchButton: [
      "inline-block",
      "h-4",
      "w-4",
      "transform",
      "rounded-full",
      "bg-white",
      "transition-transform",
      "shadow-sm",
    ],
    saveButton: [
      "bg-[#1F2A44]",
      "text-white",
      "px-6",
      "py-3",
      "rounded-xl",
      "font-semibold",
      "text-[0.875rem]",
      "hover:bg-[#2A3A5C]",
      "transition-colors",
      "font-inter",
      "mt-4",
    ],
  },
  variants: {
    switchActive: {
      true: {
        switch: "bg-[#2BD4A2]",
        switchButton: "translate-x-5",
      },
      false: {
        switch: "bg-gray-200",
        switchButton: "translate-x-1",
      },
    },
  },
});