// src/lib/styles/support.ts
import { tv } from "tailwind-variants";

export const supportVariants = tv({
  slots: {
    container: [
      "w-full",
      "max-w-[900px]",
      "mx-auto",
      "space-y-6",
      "animate-in",
      "fade-in",
      "duration-500",
    ],
    title: [
      "text-[2rem]",
      "font-bold",
      "text-[#1F2A44]",
      "mb-2",
      "font-cormorant",
    ],
    subtitle: [
      "text-[0.875rem]",
      "text-[#6B7280]",
      "mb-6",
      "font-inter",
    ],
    form: [
      "bg-white",
      "rounded-2xl",
      "p-6",
      "lg:p-8",
      "shadow-sm",
    ],
    row: [
      "grid",
      "grid-cols-1",
      "md:grid-cols-2",
      "gap-4",
      "mb-4",
    ],
    formGroup: [
      "mb-4",
    ],
    input: [
      "w-full",
      "px-4",
      "py-2.5",
      "border",
      "border-gray-200",
      "rounded-xl",
      "bg-[#F5F5F5]",
      "text-[#1F2A44]",
      "text-[0.875rem]",
      "placeholder-[#9CA3AF]",
      "font-inter",
      "focus:outline-none",
      "focus:ring-2",
      "focus:ring-[#2BD4A2]",
      "focus:border-transparent",
      "focus:bg-white",
      "transition-all",
    ],
    select: [
      "w-full",
      "px-4",
      "py-2.5",
      "border",
      "border-gray-200",
      "rounded-xl",
      "bg-[#F5F5F5]",
      "text-[#1F2A44]",
      "text-[0.875rem]",
      "font-inter",
      "focus:outline-none",
      "focus:ring-2",
      "focus:ring-[#2BD4A2]",
      "focus:border-transparent",
      "focus:bg-white",
      "appearance-none",
      "cursor-pointer",
      "transition-all",
    ],
    textarea: [
      "w-full",
      "px-4",
      "py-2.5",
      "border",
      "border-gray-200",
      "rounded-xl",
      "bg-[#F5F5F5]",
      "text-[#1F2A44]",
      "text-[0.875rem]",
      "placeholder-[#9CA3AF]",
      "font-inter",
      "focus:outline-none",
      "focus:ring-2",
      "focus:ring-[#2BD4A2]",
      "focus:border-transparent",
      "focus:bg-white",
      "resize-none",
      "min-h-[150px]",
      "transition-all",
    ],
    submitButton: [
      "bg-[#1F2A44]",
      "text-white",
      "px-8",
      "py-3",
      "rounded-xl",
      "font-semibold",
      "text-[0.875rem]",
      "hover:bg-[#2A3A5C]",
      "transition-colors",
      "font-inter",
    ],
    footer: [
      "mt-6",
      "pt-6",
      "border-t",
      "border-gray-200",
      "flex",
      "flex-wrap",
      "gap-4",
    ],
    link: [
      "text-[0.875rem]",
      "text-[#1F2A44]",
      "underline",
      "hover:text-[#2BD4A2]",
      "transition-colors",
      "font-inter",
    ],
  },
});