import { tv } from "tailwind-variants";

export const signupVariants = tv({
  slots: {
    container: [
      "w-full",
      "md:max-w-lg",
      "sm:max-w-lg",
      "px-5",
      "flex",
      "flex-col",
      "items-center",
      "animate-in",
      "fade-in",
      "slide-in-from-bottom-4",
      "duration-700",
    ],
    title: [
      "text-4xl",
      "font-bold",
      "mb-6",
      "font-cormorant",
      "text-[#1F2A44]",
      "animate-in",
      "fade-in",
      "slide-in-from-top-2",
      "duration-500",
    ],
    googleButton: [
      "flex",
      "items-center",
      "justify-center",
      "w-full",
      "gap-3",
      "mb-6",
      "rounded-lg",
      "border",
      "border-white",
      "bg-white",
      "hover:bg-gray-100",
      "transition-all",
      "duration-300",
      "hover:scale-[1.02]",
      "hover:shadow-lg",
      "active:scale-95",
      "group",
    ],
    googleIcon: [
      "w-5",
      "h-5",
      "mr-2",
      "transition-transform",
      "duration-300",
      "group-hover:rotate-12",
    ],
    dividerContainer: ["flex", "items-center", "gap-4", "my-6", "w-full"],
    dividerLine: [
      "flex-1",
      "h-[1px]",
      "bg-gradient-to-r",
      "from-transparent",
      "via-gray-300",
      "to-transparent",
    ],
    dividerText: ["text-gray-500", "font-light", "text-base", "animate-pulse"],
    errorMessage: [
      "text-sm",
      "text-red-500",
      "mb-4",
      "text-center",
      "p-3",
      "bg-red-50",
      "rounded-lg",
      "border",
      "border-red-200",
      "animate-in",
      "fade-in",
      "slide-in-from-top-2",
      "duration-300",
    ],
    form: ["flex", "flex-col", "w-full", "space-y-4"],
    inputWrapper: [
      "mb-4",
      "w-full",
      "animate-in",
      "fade-in",
      "slide-in-from-left-2",
      "duration-500",
    ],
    buttonWrapper: ["flex", "justify-center", "items-center", "my-6"],
    footer: ["flex", "flex-row", "items-center", "justify-center", "gap-3", "mt-8"],
    footerText: ["text-sm", "text-black", "font-semibold", "text-center"],
    loginLink: [
      "flex",
      "items-center",
      "gap-1",
      "group",
      "hover:scale-105",
      "transition-transform",
      "duration-200",
    ],
    loginText: [
      "text-black",
      "font-medium",
      "text-base",
      "underline",
      "group-hover:text-gray-700",
      "transition-colors",
    ],
    loginIcon: [
      "w-5",
      "h-5",
      "text-black",
      "transition-transform",
      "duration-300",
      "group-hover:translate-x-1",
    ],
    loadingContainer: [
      "flex",
      "flex-col",
      "items-center",
      "justify-center",
      "min-h-screen",
      "bg-gradient-to-b",
      "from-brand-login-bgStart",
      "to-brand-login-bgEnd",
    ],
    loadingText: ["text-lg", "text-brand-login-text", "font-inter", "animate-pulse"],
  },
});
