// src/lib/styles/packageSelection.ts
import { tv } from "tailwind-variants";

export const packageSelectionVariants = tv({
  slots: {
    container: [
      "flex",
      "flex-col",
      "items-center",
      "px-4",
      "py-8",
      "min-h-screen",
      "bg-gradient-to-b",
      "from-[#E8E4E1]",
      "via-[#F5F3F1]",
      "to-white",
      "md:px-8",
      "md:py-16",
    ],
    header: [
      "w-full",
      "max-w-[1200px]",
      "text-center",
      "mb-12",
      "md:mb-16",
    ],
    title: [
      "text-[2rem]",
      "font-bold",
      "text-[#1F2A44]",
      "leading-tight",
      "mb-2",
      "md:text-[2.5rem]",
      "font-cormorant",
    ],
    subtitle: [
      "text-[0.875rem]",
      "text-[#6B7280]",
      "md:text-[1rem]",
      "font-inter",
    ],
    packagesWrapper: [
      "flex",
      "flex-col",
      "gap-6",
      "w-full",
      "max-w-[1200px]",
      "mb-16",
      "md:flex-row",
      "md:gap-8",
    ],
    packageCard: [
      "relative",
      "bg-white",
      "rounded-2xl",
      "p-6",
      "transition-all",
      "duration-300",
      "md:p-8",
    ],
    badge: [
      "absolute",
      "top-4",
      "right-4",
      "text-[0.625rem]",
      "font-medium",
      "px-2",
      "py-1",
      "rounded",
      "uppercase",
      "tracking-wide",
      "font-inter",
    ],
    packageHeader: [
      "flex",
      "items-baseline",
      "gap-2",
      "mb-4",
    ],
    packageTitle: [
      "text-[1.25rem]",
      "font-bold",
      "text-[#1F2A44]",
      "md:text-[1.5rem]",
      "font-cormorant",
    ],
    packagePrice: [
      "text-[2rem]",
      "font-bold",
      "text-[#1F2A44]",
      "md:text-[2.25rem]",
      "font-inter",
    ],
    priceLabel: [
      "text-[0.75rem]",
      "text-[#6B7280]",
      "font-inter",
    ],
    featuresList: [
      "space-y-3",
      "mb-6",
    ],
    featureItem: [
      "flex",
      "items-start",
      "gap-2",
      "text-[0.875rem]",
      "text-[#1F2A44]",
      "leading-relaxed",
      "md:text-[0.9375rem]",
      "font-inter",
    ],
    checkIcon: [
      "w-5",
      "h-5",
      "flex-shrink-0",
      "mt-0.5",
    ],
    buttonWrapper: [
      "space-y-2",
    ],
    chooseButton: [
      "w-full",
      "py-3",
      "rounded-xl",
      "font-medium",
      "text-[0.9375rem]",
      "transition-all",
      "duration-200",
      "font-inter",
    ],
    paymentNote: [
      "text-center",
      "text-[0.75rem]",
      "text-[#9CA3AF]",
      "font-inter",
    ],
    detailsSection: [
      "w-full",
      "max-w-[1200px]",
      "bg-white/80",
      "backdrop-blur-sm",
      "rounded-2xl",
      "p-6",
      "md:p-12",
    ],
    detailsTitle: [
      "text-[1.25rem]",
      "font-bold",
      "text-[#1F2A44]",
      "text-center",
      "mb-8",
      "md:text-[1.5rem]",
      "font-cormorant",
    ],
    detailsGrid: [
      "grid",
      "grid-cols-1",
      "gap-6",
      "sm:grid-cols-2",
      "md:grid-cols-4",
      "md:gap-8",
    ],
    detailItem: [
      "text-center",
    ],
    detailIconWrapper: [
      "flex",
      "justify-center",
      "mb-3",
    ],
    detailCheckIcon: [
      "w-8",
      "h-8",
      "text-[#22C55E]",
    ],
    detailHeader: [
      "text-[0.9375rem]",
      "font-semibold",
      "text-[#1F2A44]",
      "mb-2",
      "font-inter",
    ],
    detailDescription: [
      "text-[0.8125rem]",
      "text-[#6B7280]",
      "leading-relaxed",
      "font-inter",
    ],
  },
  variants: {
    featured: {
      true: {
        packageCard: [
          "border-2",
          "border-[#2BD4A2]",
          "shadow-lg",
          "shadow-[#2BD4A2]/20",
          "scale-105",
        ],
        badge: [
          "bg-[#2BD4A2]",
          "text-white",
        ],
        chooseButton: [
          "bg-[#1F2A44]",
          "text-white",
          "hover:bg-[#2A3A5C]",
          "shadow-md",
        ],
        checkIcon: [
          "text-[#2BD4A2]",
        ],
      },
      false: {
        packageCard: [
          "border",
          "border-gray-200",
          "hover:border-gray-300",
          "hover:shadow-md",
        ],
        badge: [
          "bg-gray-100",
          "text-gray-600",
        ],
        chooseButton: [
          "bg-white",
          "text-[#1F2A44]",
          "border-2",
          "border-[#1F2A44]",
          "hover:bg-[#1F2A44]",
          "hover:text-white",
        ],
        checkIcon: [
          "text-[#22C55E]",
        ],
      },
    },
  },
});