import { tv } from "tailwind-variants";

export const ancestryStepVariants = tv({
  slots: {
    container: [
      "flex",
      "flex-col",
      "gap-[1.5rem]",
    ],
    questionWrapper: [
      "flex",
      "flex-col",
      "gap-[0.5rem]",
    ],
    label: [
      "text-[#1F2A44]",
      "font-medium",
      "text-[0.875rem]",
      "leading-[1.25rem]",
      "md:text-[1rem]",
      "md:leading-[1.5rem]",
      "font-inter",
    ],
    checkboxGroup: [
      "flex",
      "gap-[1rem]",
    ],
    checkboxLabel: [
      "flex",
      "items-center",
      "gap-[0.5rem]",
    ],
    checkbox: [
      "w-[1rem]",
      "h-[1rem]",
      "text-[#03BCA3]",
    ],
    checkboxText: [
      "text-[0.875rem]",
      "text-[#1F2A44]",
      "font-inter",
    ],
    relativesContainer: [
      "flex",
      "flex-col",
      "gap-[1rem]",
    ],
    relativeRow: [
      "flex",
      "flex-col",
      "gap-[0.5rem]",
      "sm:flex-row",
      "sm:gap-[1rem]",
    ],
    inputWrapper: [
      "flex-1",
    ],
    input: [
      "w-full",
      "px-[1rem]",
      "py-[0.75rem]",
      "bg-[#E5DEDB]",
      "rounded-[0.5rem]",
      "text-[#1F2A44]",
      "text-[1rem]",
      "font-medium",
      "placeholder-[#6B7280]",
      "outline-none",
      "focus:border-[#03BCA3]",
      "focus:ring-[0.0625rem]",
      "focus:ring-[#03BCA3]",
      "font-inter",
    ],
    removeButton: [
      "self-end",
      "text-[#6B7280]",
      "hover:text-[#1F2A44]",
      "mt-[1.5rem]",
    ],
    removeIcon: [
      "w-[1rem]",
      "h-[1rem]",
    ],
    addButton: [
      "flex",
      "items-center",
      "gap-[0.5rem]",
      "text-[#1F2A44]",
      "hover:text-[#03BCA3]",
    ],
    addIcon: [
      "w-[1rem]",
      "h-[1rem]",
    ],
    addText: [
      "text-[0.875rem]",
      "font-medium",
      "font-inter",
    ],
  },
});


export const educationStepVariants = tv({
  slots: {
    container: [
      "flex",
      "flex-col",
      "gap-[1.5rem]",
    ],
    questionWrapper: [
      "flex",
      "flex-col",
      "gap-[0.5rem]",
    ],
    label: [
      "text-[#1F2A44]",
      "font-medium",
      "text-[0.875rem]",
      "leading-[1.25rem]",
      "md:text-[1rem]",
      "md:leading-[1.5rem]",
      "font-inter",
    ],
    input: [
      "px-[1rem]",
      "py-[0.75rem]",
      "bg-[#E5DEDB]",
      "rounded-[0.5rem]",
      "text-[#1F2A44]",
      "text-[1rem]",
      "font-medium",
      "placeholder-[#6B7280]",
      "outline-none",
      "focus:border-[#03BCA3]",
      "focus:ring-[0.0625rem]",
      "focus:ring-[#03BCA3]",
      "font-inter",
    ],
    checkboxGroup: [
      "flex",
      "gap-[1rem]",
    ],
    checkboxLabel: [
      "flex",
      "items-center",
      "gap-[0.5rem]",
    ],
    checkbox: [
      "w-[1rem]",
      "h-[1rem]",
      "text-[#03BCA3]",
    ],
    checkboxText: [
      "text-[0.875rem]",
      "text-[#1F2A44]",
      "font-inter",
    ],
    errorText: [
      "text-[0.75rem]",
      "text-red-500",
      "mt-[0.25rem]",
      "font-inter",
    ],
  },
});

export  const familyStepVariants = tv({
  slots: {
    container: [
      "flex",
      "flex-col",
      "gap-[1.5rem]",
    ],
    questionWrapper: [
      "flex",
      "flex-col",
      "gap-[0.5rem]",
    ],
    label: [
      "text-[#1F2A44]",
      "font-medium",
      "text-[0.875rem]",
      "leading-[1.25rem]",
      "md:text-[1rem]",
      "md:leading-[1.5rem]",
      "font-inter",
    ],
    radioGroup: [
      "flex",
      "gap-[1rem]",
    ],
    radioLabel: [
      "flex",
      "items-center",
      "gap-[0.5rem]",
    ],
    radio: [
      "w-[1rem]",
      "h-[1rem]",
      "text-[#03BCA3]",
    ],
    radioText: [
      "text-[0.875rem]",
      "text-[#1F2A44]",
      "font-inter",
    ],
    checkboxGroup: [
      "flex",
      "gap-[1rem]",
    ],
    checkboxLabel: [
      "flex",
      "items-center",
      "gap-[0.5rem]",
    ],
    checkbox: [
      "w-[1rem]",
      "h-[1rem]",
      "text-[#03BCA3]",
    ],
    checkboxText: [
      "text-[0.875rem]",
      "text-[#1F2A44]",
      "font-inter",
    ],
    errorText: [
      "text-[0.75rem]",
      "text-red-500",
      "mt-[0.25rem]",
      "font-inter",
    ],
  },
});


export const generalStepVariants = tv({
  slots: {
    outerContainer: [
      "w-full",
      "max-w-[1200px]",
      "mx-auto",
      "min-h-[100svh]",
      "px-[1rem]",
      "sm:px-[3rem]",
    ],
    contentWrapper: [
      "p-[1rem]",
      "md:p-[2.5rem]",
      "overflow-y-auto",
    ],
    formGrid: [
      "grid",
      "grid-cols-1",
      "md:grid-cols-[1fr_2fr]",
      "gap-y-[1.5rem]",
      "md:gap-x-[2rem]",
      "md:gap-y-[2rem]",
    ],
    labelColumn: [
      "flex",
      "flex-col",
      "gap-[0.5rem]",
    ],
    inputColumn: [
      "flex",
      "flex-col",
      "gap-[0.5rem]",
    ],
    label: [
      "text-[#1F2A44]",
      "font-medium",
      "text-[0.875rem]",
      "leading-[1.25rem]",
      "md:text-[1rem]",
      "md:leading-[1.5rem]",
      "font-inter",
    ],
    required: [
      "text-[#EF4444]",
    ],
    inputBase: [
      "w-full",
      "min-h-[3rem]",
      "px-[0.75rem]",
      "py-[0.5rem]",
      "text-[0.875rem]",
      "text-[#1F2A44]",
      "bg-[#F0EDEB]",
      "border-[0.0625rem]",
      "border-[#D1D5DB]",
      "rounded-[0.5rem]",
      "focus:outline-none",
      "focus:ring-[0.125rem]",
      "focus:ring-[#22C55E]",
      "focus:border-[#22C55E]",
      "transition-all",
      "duration-200",
      "placeholder:text-[#9CA3AF]",
      "md:text-[1rem]",
      "font-inter",
    ],
    numberInput: [
      "w-full",
      "h-[3rem]",
      "px-[0.75rem]",
      "py-[0.5rem]",
      "text-[0.875rem]",
      "text-[#1F2A44]",
      "bg-[#F0EDEB]",
      "border-[0.0625rem]",
      "border-[#D1D5DB]",
      "rounded-[0.5rem]",
      "focus:outline-none",
      "focus:ring-[0.125rem]",
      "focus:ring-[#22C55E]",
      "focus:border-[#22C55E]",
      "transition-all",
      "duration-200",
      "placeholder:text-[#9CA3AF]",
      "md:text-[1rem]",
      "font-inter",
    ],
    homeSizeRow: [
      "flex",
      "flex-col",
      "gap-[0.5rem]",
      "sm:flex-row",
      "sm:gap-[1rem]",
    ],
    regionsButtonsWrapper: [
      "flex",
      "flex-wrap",
      "gap-[0.5rem]",
    ],
    regionButton: [
      "min-w-[8rem]",
      "h-[2.5rem]",
      "px-[1rem]",
      "py-[0.5rem]",
      "border-[0.0625rem]",
      "rounded-[0.5rem]",
      "text-[0.875rem]",
      "font-medium",
      "transition-colors",
      "duration-200",
      "focus:outline-none",
      "focus:ring-[0.125rem]",
      "focus:ring-[#22C55E]",
      "focus:ring-offset-[0.0625rem]",
      "md:text-[1rem]",
      "font-inter",
    ],
    errorText: [
      "text-[0.75rem]",
      "text-[#EF4444]",
      "mt-[0.25rem]",
      "font-inter",
    ],
    navigationWrapper: [
      "md:col-span-2",
    ],
  },
  variants: {
    regionSelected: {
      true: {
        regionButton: [
          "bg-[#22C55E]",
          "text-white",
          "border-[#22C55E]",
          "hover:bg-[#20b356]",
        ],
      },
      false: {
        regionButton: [
          "bg-white",
          "text-[#1F2A44]",
          "border-[#D1D5DB]",
          "hover:bg-[#F3F4F6]",
        ],
      },
    },
  },
});

export const workStepVariants = tv({
  slots: {
    container: [
      "flex",
      "flex-col",
      "gap-[1.5rem]",
      "animate-in",
      "fade-in",
      "duration-500",
    ],
    questionWrapper: [
      "flex",
      "flex-col",
      "gap-[0.5rem]",
      "animate-in",
      "slide-in-from-left-2",
      "duration-300",
    ],
    label: [
      "text-[#1F2A44]",
      "font-medium",
      "text-[0.875rem]",
      "leading-[1.25rem]",
      "md:text-[1rem]",
      "md:leading-[1.5rem]",
      "font-inter",
    ],
    required: [
      "text-red-500",
    ],
    radioGroup: [
      "flex",
      "flex-wrap",
      "gap-[1rem]",
    ],
    radioLabel: [
      "flex",
      "items-center",
      "gap-[0.5rem]",
      "cursor-pointer",
      "group",
    ],
    radio: [
      "w-[1rem]",
      "h-[1rem]",
      "text-[#03BCA3]",
      "cursor-pointer",
      "transition-transform",
      "group-hover:scale-110",
    ],
    radioText: [
      "text-[0.875rem]",
      "text-[#1F2A44]",
      "font-inter",
      "transition-colors",
      "group-hover:text-[#03BCA3]",
    ],
    checkboxGroup: [
      "flex",
      "gap-[1rem]",
    ],
    checkboxLabel: [
      "flex",
      "items-center",
      "gap-[0.5rem]",
      "cursor-pointer",
      "group",
    ],
    checkbox: [
      "w-[1rem]",
      "h-[1rem]",
      "text-[#03BCA3]",
      "cursor-pointer",
      "transition-transform",
      "group-hover:scale-110",
    ],
    checkboxText: [
      "text-[0.875rem]",
      "text-[#1F2A44]",
      "font-inter",
      "transition-colors",
      "group-hover:text-[#03BCA3]",
    ],
    input: [
      "px-[1rem]",
      "py-[0.75rem]",
      "bg-[#E5DEDB]",
      "rounded-[0.5rem]",
      "text-[#1F2A44]",
      "text-[1rem]",
      "font-medium",
      "placeholder-[#6B7280]",
      "outline-none",
      "border-2",
      "border-transparent",
      "font-inter",
      "transition-all",
      "duration-200",
      "focus:border-[#03BCA3]",
      "focus:ring-[0.0625rem]",
      "focus:ring-[#03BCA3]",
      "focus:bg-white",
    ],
    errorText: [
      "text-[0.75rem]",
      "text-red-500",
      "mt-[0.25rem]",
      "font-inter",
      "animate-in",
      "slide-in-from-top-1",
      "duration-200",
    ],
    infoCard: [
      "p-4",
      "bg-blue-50",
      "border",
      "border-blue-200",
      "rounded-lg",
      "mt-2",
    ],
    infoText: [
      "text-[0.875rem]",
      "text-blue-800",
      "font-inter",
    ],
    inputGroup: [
      "relative",
    ],
    currencySymbol: [
      "absolute",
      "left-4",
      "top-1/2",
      "-translate-y-1/2",
      "text-[#6B7280]",
      "font-inter",
    ],
    inputWithIcon: [
      "pl-8",
    ],
  },
});